version: '3'
services:
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data/mysql:/var/lib/mysql
      - ./mysql/confs/dev/mysql:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somepass123
      MYSQL_DATABASE: examples
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    ports:
      - 3308:3306
  manticore:
    build: ./manticore
    volumes:
      - ./manticore/etc/:/etc/sphinxsearch
      - ./manticore/data/:/var/lib/manticore/data
      - ./manticore/logs/:/var/log/manticore
    environment:
      MANTICORE_VERSION: 3.1.2
    ports:
      - 9306:9306
      - 9308:9308
      - 9312:9312
    depends_on:
      - mysql
  site:
    build: ./apache-php
    volumes: 
      - ./apache-php/public_html:/var/www/site
    ports: 
      - 5000:80
    depends_on:
      - manticore